eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8762/eureka/}
server:
    port: 8082
spring:
  application:
    name: Config-Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xmlriz/springBoot-config-server.git
          clone-on-start: true